// Copyright Fastly, Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by mdatagen. DO NOT EDIT.

// Package metadata contains the autogenerated telemetry and
// build information for the receiver/tetragon component.
package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("tetragon")
	ScopeName = "github.com/fastly/tetragon-receiver"
)

const (
	LogsStability = component.StabilityLevelDevelopment
)
